### ISSUE TITLE
Pan arrow keys aren't "repeatable"

### ISSUE THREAD

**Issue by eugenesvk** [woelper/oculante#109]
For example, holding <kbd>◀</kbd> to pan left only moves the picture once

**Comment by woelper** [comment]
Yes. This is a result of the new shortcut system. If it were instantly repeating, it would be hard to check for released other keys.

**Comment by eugenesvk** [comment]
Oh, the no-repeat is fine as a general rule/for the alpha keys (I also have the repeat disabled for them system-wide as, e.g., press&hold is a much more useful alternative; just like using <kbd>c</kbd> in Oculante is much more useful as a modifier for color channels than whatever the repeat could be there), but the arrow keys are a bit special, they should be excluded and always repeat

**Comment by woelper** [comment]
The problem here is that after oculante moved to a customizable shortcut system, it's much harder to just exclude things. You have to match any keypress to a command somehow. 

For this to work, you have to observe what is pressed and released at any given moment in time. You can for example query the keys which were released on the last frame and those which are currently down (more here https://docs.rs/notan_input/latest/notan_input/keyboard/struct.Keyboard.html)

Let's say you have bound `cmd+shift+a+b+c` to pan left. You can't immediately repeat after any keystroke, as you have to wait until that combination has been pressed. At the same time, you want something else to happen only when `a` is pressed, and another thing when you press `shift+a`.

If you have any good suggestion how to make this work in a better way, I'd be very happy to hear it!

Maybe limiting the amount of keypresses to just one key and modifiers would make it easier as you just have to query if any of those is down. But this would prevent you from setting up channel shortcuts like `c+1`.

**Comment by eugenesvk** [comment]
(more __specific__) in this request I meant just the literal <kbd>◀</kbd><kbd>▲</kbd><kbd>▼</kbd><kbd>▶</kbd> arrow keys, not if you rebind <kbd>l</kbd> to be a `PanLeft` function, so the literal arrows don't suffer from the complication you raised, right?

(more __general__, assuming that the arrows keys can work without this fix)
Some __workarounds__ that would reduce the need for key repetition
  - adding <kbd>⇧</kbd><kbd>◀</kbd> for medium dinstance pan
  - adding <kbd>⌃</kbd><kbd>◀</kbd> for large distance pan

Worst case, I could re-add the awesomeness of <kbd>c</kbd><kbd>1</kbd> via a keyboard remapping app (once conflicts are resolved, see my issues with karabiner opened elsewhere), though an in-app solution is much better for x-platform compatibility

Now, in your example I don't fully understand the issue. Just for clarify, let's assume that you have to explicitly enable `repeatable` for a given function/keybind (most functions aren't repeatable anyway, e.g., `fullscreen` shouldn't flash if you hold <kbd>f</kbd>, etc.), so you have the following keybinds:
  - (repeatable toggle on) hold<kbd>⌘</kbd>h<kbd>⇧</kbd>h<kbd>a</kbd>h<kbd>b</kbd> + tap<kbd>l</kbd> is mapped to `PanLeft` (I don't see any practical way of treating multiple alpha keys unless you treat all but one as 'modifiers', so in this case holding all the other keys and tapping <kbd>l</kbd> should pan left, but holding all the keys (including <kbd>l</kbd>) and tapping <kbd>a</kbd> does nothing the same way as <kbd>⌘</kbd><kbd>l</kbd> doesn't work when you hold <kbd>l</kbd> and tap <kbd>⌘</kbd>)
    - due to repeatable toggle, hold <kbd>l</kbd> in the ↑ keybind should continue to `PanLeft` as long as you continue to hold
  - (repeatable toggle on) <kbd>a</kbd> to switch to a previous image
    - ↑ should (repeatedly) work right away, no need to wait for anything else, "proper" modifiers are always expected to be pressed first before a key
  - (repeatable toggle on) <kbd>⇧</kbd><kbd>a</kbd> to zoom in
    - ↑ same, should work right away
  - (repeatable toggle on) <kbd>⇧</kbd><kbd>⌘</kbd><kbd>a</kbd> to zoom out
    - ↑ is more complicated since you have a key that is both a tap-key and a modifier-key. But then is this not the same as https://github.com/woelper/oculante/issues/105, where for such dual alpha-keys you 'just' need to move the main function to `onRelease`?
    - another workaround for the __repeatable__ functionality that won't be solved with ↑ `onRelease`: add a delay, so if the user doesn't press the additional <kbd>b</kbd> modifier within `1s`, then zoom out starts to repeat function (not sure this "over-engineering" is worth it, though, think you'd need a non-artificial example to see its value)

Or am I missing something, and there is some other conflict?

**Comment by woelper** [comment]
> (more specific) in this request I meant just the literal arrow_backward▲▼arrow_forward arrow keys, not if you rebind l to be a PanLeft function, so the literal arrows don't suffer from the complication you raised, right?

No, they suffer from the complication:

There are no differences between keys right now, so it does not matter if it is an arrow key or something else. All keys are treated the same. The system now works like this:
- Input event happens
- get the keys currently pressed
- look up the corresponding command
- execute command

Since I have no way to know before what combination of keys a user has bound to a command, the difficulty is to reliably detect any combination of keys.

Another issue is that to avoid scanning keys each frame, I perform actions when a key is pressed or released. There is no such an event if a key is held I believe. For this to work, I would have to check every frame if the key is still held. As I don't know the specific key (user could have entered any combo) this would complicate matters a bit and might even affect performance.

**Comment by woelper** [comment]
Oh, I just figured something out to detect if a key is still down, and I believe I can hardcode reapeating keys for a set of commands... I'll report back if I have something.

**Comment by eugenesvk** [comment]
> Another issue is that to avoid scanning keys each frame, I perform actions when a key is pressed or released. There is no such an event if a key is held I believe.

Oh, I see, then that's the real complication!

> For this to work, I would have to check every frame if the key is still held. As I don't know the specific key (user could have entered any combo) this would complicate matters a bit and might even affect performance.

That's what I meant by "arrows are special", you'd only need to track it for "repeatable" keys, i.e., arrow keys; so if you bind panning to non-arrow keys, it would not be repeatable anymore!

Or maybe you could just set a `arrow_key_down` variable to `1` when a key is down and then repeat an action until that key is released, then the variable is set back to `0`. This way you don't need to scan the status of each key on each frame, but continue to check only the key_up/down events, and this key var status in the meantime?

**Comment by woelper** [comment]
I have a working version now, but for some reason keys that have modifiers (like shift+right) have a slight "lag" - it seems that they still trigger after they are up. It's not super bad, and not an issue if it's a single repeating key. I'll see if I can find out more.

> That's what I meant by "arrows are special", you'd only need to track it for "repeatable" keys, i.e., arrow keys; so if you bind panning to non-arrow keys, it would not be repeatable anymore!

You could bind Arrow keys to non-repeatable actions, like fullscreen - so basing it on keys will probably not work. What I do now is to track for repeatable commands.

**Comment by eugenesvk** [comment]
> You could bind Arrow keys to non-repeatable actions, like fullscreen - so basing it on keys will probably not work

But you can check whether the command is repeatable or not later after you've got the key event (and not repeat if it's fullscreen), so that's not an issue, and you still get the benefit of only tracking a few keys

**Comment by woelper** [comment]
> But you can check whether the command is repeatable or not later after you've got the key event (and not repeat if it's fullscreen), so that's not an issue, and you still get the benefit of only tracking a few keys

Yes, that is what I've been doing. I've merged that and will release soon. As said, it's imperfect when you have multiple keys bound (+ - works perfectly, shift left/right lags a bit). This is still better than non-repeating keys.
