### ISSUE TITLE
PanUp/Down symmetry is the opposite of PanLeft/Right

### ISSUE THREAD

**Issue by eugenesvk** [woelper/oculante#110]
`PanLeft` moves the pic left, but `PanUp` moves the picture down, so I have to bind it to <kbd>▼</kbd> to make it function like the left/right pair

<img width="250" alt="ocul_pan" src="https://user-images.githubusercontent.com/12956286/210218022-82de4357-6789-4cc8-bae4-f623c62beffd.png">

**Comment by brian6932** [comment]
This was fixed, but they're all still reversed from what I'd expect.
- Panning up moves the image up, instead of moving the camera up.
- Panning down moves the image down, instead of moving the camera down.
- Panning left moves the left down, instead of moving the camera left.
- Panning right moves the image right, instead of moving the camera right.

Panning's the action of moving a camera, not the image: https://en.wikipedia.org/wiki/Panning_(camera).
