### ISSUE TITLE
Behavior change - interesting finding

### ISSUE THREAD

**Issue by 0323pin** [woelper/oculante#190]
Hi,

We (NetBSD) have a recent behavior change in the way we package and install Rust applications.

Before we used to just run `cargo build --offline --release` and install the resulting binary in `target/release` to the correct system location.

We have changed this recently and, I should say, it doesn't work for all the packages but, `oculante` has shown an interesting behavior.

Basically, we still run `cargo build --offline --release` but, then instead of moving the resulting binary, we let `cargo` do this by calling `cargo-install`.

Think about it like "make" = `cargo build --offline --release` and "make install" = `cargo-install`.

When running the `cargo install` phase with `oculante`, it re-starts the build which, `cargo build --offline --release` just finished.
It doesn't rebuild any of the crate dependencies, just the main binary but, this adds to the total build time. For now, I've decided to keep the old install format and save build time.

Thoughts?!
Thanks

**Comment by woelper** [comment]
I can only guess - this could be because of `build.rs` leaving the repo/folder dirty and triggering a rebuild, or this could be because of optimisations specified in `Cargo.toml` which somehow cause to re-build or re-link the executable.
To test this, delete the `build.rs`, and another try, you could remove the whole `[profile.release]` section in the `Cargo.toml`.

**Comment by 0323pin** [comment]
Thanks, I'll give it a try by the next update.
