### ISSUE TITLE
'Insufficient memory' error when opening a 16 MB image

### ISSUE THREAD

**Issue by rikako3** [woelper/oculante#198]
If I try to open the following image with Oculante 0.6.65 on Windows 11, I get an "insufficient memory" error: https://mega.nz/file/GEdnRCZb#kcLtHYomjqn0fz10FEVCKzOjVSrGyTaEjd8iU20dMqs

**Comment by woelper** [comment]
Thanks for reporting. I think this is something with limits in the decoder. I'll try to find a fix.

**Comment by woelper** [comment]
There were no limits set in the decoder. it seems that this image has some weird data in it - some other image viewers I tested also failed. I will investigate another png library in the future.

**Comment by Quackdoc** [comment]
I'm also verifying this with image-rs test file I have. the file size might be too much for it to decode and it may be tripping a hard limit? 

for the sake of clarity for reporter, the insufficient memory doesn't have anything to do with the compressed size, it's ram usage for decoding the image, which could be fairly large considering the size, but it wouldn't be THAT much I would assume this is an issue with the decoder itself running into a memory leak.

It might be worth reporting to image-png. Im curious if this is due to pixel aspect ratio `SAR 2835:2835 DAR 5000:2407` `Storage aspect ratio/Display Aspect Ratio` this means that the image is physically a `2835x2835` resolution image but when decoded it should be decoded as `5000x2407` this isn't super common but I wonder if this could be causing an absurdly high memory decode usage that could be tripping image-png regardless, possible solution related to  #183

**Comment by woelper** [comment]
I am actually in the process of testing zune-png just for png loading. It loads the above image just fine without errors. It is a bit slower in my tests (384ms vs 247ms load time for a large image), but I am leaning towards better file support in favor of slower load time currently.

**Comment by woelper** [comment]
I switched to zune-png now and tested with a large number of png sample images. The next release will have this as the default.
