### ISSUE TITLE
HEIF support

### ISSUE THREAD

**Issue by fabienengels** [woelper/oculante#237]
Hi,
Would be possible to add heif image support ? Maybe via https://docs.rs/libheif-rs/latest/libheif_rs/ ?

Thank you in advance

**Comment by woelper** [comment]
Hi! I am always open to add more formats, and adding them was quite easy in the past. From some quick reading, the main problem with heif is it's license and the fact that no native rust library. This can be difficult when the goal is shipping one static binary, and also when building on CI, especially for non x86_64 systems, Windows and MacOS. I'll give it a try!

**Comment by woelper** [comment]
Update:
Getting HEIC/HEIF in was quite straightforward, although I have come across some formats that could not be decoded. I even for fun let the avif decoder handle some, and that worked for select files, too.

The problem is building the library on CI - the github runners' ubuntu version include an older version of libheif that fails the build. Windows also fails, Armv7 fails and NetBSD fails. The only thing working is MacOS as of now.

**Comment by fabienengels** [comment]
Thank you for your quick answers and your work, let's hope the situation evolves (no one to code a rust heif lib ? ;D)

**Comment by woelper** [comment]
I have successfully enabled this on linux and mac CI and plan to merge it at least for these as default soon.
