### ISSUE TITLE
Use `.config` instead of `.local/share` for config on linux

### ISSUE THREAD

**Issue by Gigas002** [woelper/oculante#289]
Continuation of what's been discussed in #284 . Shouldn't be hard to implement, requires changes in `settings.rs` from `data_local_dir` to `config_local_dir`.
Personally I'd like the path to be changed from `~/.config/.oculante` to `~/.config/oculante/config.json` so it includes `oculante` as dir and makes it easier to `cd` into, but I guess that my taste preferences. Besides, this change would be breaking for `macOS`/`windows` users (straight changing from `data_local_dir` to `config_local_dir` is not) so yeah, I guess not.
Some migration for linux users _may be_ needed though.

**Comment by woelper** [comment]
Thanks for opening this! Will address this soon!

**Comment by bartlibert** [comment]
It seems this was reverted with commit cc27bc3ab86e86b5b65d4d4a30e41dfdea20d2ba, is there any reason for this, the commit message is not clear? `~/.config/oculante/config.json` feels more "right" on linux :(

**Comment by Stoppedpuma** [comment]
The reason for this was that Oculante has roots in being a portable application. Me and woelper agreed that it was better to have a single data folder to transfer between systems instead of leaving several files across the system. The data folder will hold more things like LUTs and brushes in the future.
