### ISSUE TITLE
Add shortcut to toggle UI

### ISSUE THREAD

**Issue by woelper** [woelper/oculante#43]
There should be a keyboard shortcut (Tab?) with command line flag to hide all UI.

**Comment by eugenesvk** [comment]
Just moving my comment from another issue to a more appropriate place.
Please add a **truly borderless** mode by adding two options that would allow  the following UI modifications:
- Disable the standard **window titlebar** from being created when a new app instance is launched
- Disable the standard **window resize border** from being created when a new app instance is launched

On Windows, it would mean unsetting the following window masks (or at least that's my workaround with Autohotkey, )
```
WS_Caption   	:= 0x00C00000           	; Title bar    	(WS_BORDER + WS_DLGFRAME)
WS_SizeBox   	:= 0x00040000           	; Sizing border	(=WS_THICKFRAME)
WS_Borderless	:= WS_Caption|WS_SizeBox	; BitwiseOR    	(logical inclusive OR)
```

So you get this semi-pure (since the toolbar is still there ;)) joy of your mouse cursor not flashing over the border and not titlebars
<img width="166" alt="win" src="https://user-images.githubusercontent.com/12956286/208596385-33282845-90c7-4871-931b-7704a937e8d4.png">

**Comment by woelper** [comment]
This is now possible in "Zen mode". I've made a separate issue for borderless mode. I've gotten quite far with borderless mode, but the main problem is _moving_ the window.
